#define NABTO_SET_TIME_FROM_ALIVE 0
#define NABTO_LOG_ALL 1

#define NABTO_CONNECTIONS_SIZE 100
#define NABTO_STREAM_MAX_STREAMS 100
//#define NABTO_STREAM_SEND_WINDOW_SIZE 10000
#define NABTO_STREAM_RECEIVE_WINDOW_SIZE 1000

#ifdef ENABLE_TCP_FALLBACK
#define NABTO_ENABLE_TCP_FALLBACK 1
#endif
